name: Informed.Repo.CredentialScan.Verified.CI

on: push

jobs:

  check-for-credentials:
    runs-on: ubuntu-latest
    container: trufflesecurity/trufflehog:latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Scan for credentials
        run:
          trufflehog git file://./ --only-verified --since-commit ${{ github.event.repository.default_branch }} --branch HEAD --no-update --fail > /dev/null