name: Informed.Repo.CredentialScan.Verified.CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  check-for-credentials:
    runs-on: ubuntu-latest
    container: trufflesecurity/trufflehog:latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PR - Scan for credentials
        if: github.event_name == 'pull_request'
        run:
          trufflehog git file://. --only-verified --branch ${{ github.event.pull_request.head.ref }} --no-update --fail

      - name: PR - Scan for UNVERIFIED credentials
        if: github.event_name == 'pull_request'
        run:
          trufflehog git file://. --branch ${{ github.event.pull_request.head.ref }} --no-update


      - name: Push - Scan for credentials
        if: github.event_name == 'push'
        run:
          trufflehog git file://. --only-verified --branch ${{ github.event.ref }} --no-update --fail

      - name: Push - Scan for UNVERIFIED credentials
        if: github.event_name == 'push'
        run:
          trufflehog git file://. --branch ${{ github.event.ref }} --no-update