name: Informed.Repo.CredentialScan.Verified.CI

on:
  push:
  pull_request:

jobs:

  check-for-credentials:
    runs-on: ubuntu-latest
    container: trufflesecurity/trufflehog:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning - Verified
        run: trufflehog git file://./ --only-verified --no-update --fail || echo "No verified credentials found."

      - name: Secret Scanning - Unverified
        run: trufflehog git file://./ --no-update || echo "No unverified credentials found."